kevin-lee/logger-f

- core/src/main/scala/just/effect/ConsoleEffect.scala
- core/src/main/scala/loggerf/LoggerA.scala
- core/src/main/scala/loggerf/LoggerEither.scala
- core/src/main/scala/loggerf/LoggerOption.scala
- core/src/main/scala/loggerf/Loggers.scala
Fixed: Warts detected by the wart remover plugin
> Fixed: Warts detected by the wart remover plugin

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-simple.sh
- .github/workflows/sbt-build.sh
- build.sbt
Added: GitHub Actions config and script files
> Added: GitHub Actions config and script files

- core/src/main/scala/just/effect/ConsoleEffectful.scala
Added: `ConsoleEffectful` `object`
> Added: ConsoleEffectful object

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/task-template.md
> Added: GitHub issue templates

- .github/PULL_REQUEST_TEMPLATE/pr.md
- .github/PULL_REQUEST_TEMPLATE/release.md
- .github/PULL_REQUEST_TEMPLATE/release_to_master.md
> Added: GitHub PR templates

- .github/pull_request_template.md
> Added: PR template

- .github/workflows/release.yml
Changed: GitHub Actions - env var name for release
> Changed: GitHub Actions - env var name for release

- docs/docs/index.md
- docs/microsite/data/menu.yml
Added: initial doc config and index
> Added: initial doc config and index

- build.sbt
> Use released Effectie

- build.sbt
> Use WartRemover in IDE

- core/src/main/scala/loggerf/Logful.scala
- core/src/main/scala/loggerf/LoggerOptionT.scala
- core/src/main/scala/loggerf/Loggers.scala
> Added: LoggerOptionT

- core/src/main/scala/loggerf/Logful.scala
- core/src/main/scala/loggerf/LoggerEitherT.scala
- core/src/main/scala/loggerf/Loggers.scala
> Added: LoggerEitherT

- core/src/main/scala/loggerf/Log.scala
- core/src/main/scala/loggerf/Logful.scala
- core/src/main/scala/loggerf/Loggers.scala
Close #22 - Add log with log level
> Close #22 - Add log with log level

- build.sbt
- scalaz-effect/src/main/scala/loggerf/Log.scala
- scalaz-effect/src/main/scala/loggerf/Log4jLogger.scala
- scalaz-effect/src/main/scala/loggerf/Logful.scala
- scalaz-effect/src/main/scala/loggerf/Logger.scala
- scalaz-effect/src/main/scala/loggerf/LoggerA.scala
- scalaz-effect/src/main/scala/loggerf/LoggerEither.scala
- scalaz-effect/src/main/scala/loggerf/LoggerEitherT.scala
- scalaz-effect/src/main/scala/loggerf/LoggerOption.scala
- scalaz-effect/src/main/scala/loggerf/LoggerOptionT.scala
- scalaz-effect/src/main/scala/loggerf/Loggers.scala
- scalaz-effect/src/main/scala/loggerf/Slf4JLogger.scala
Added: Logger-F for Scalaz-Effect
> Added: Logger-F-Scalaz-Effect

- cats-effect/src/main/scala/loggerf/cats/Log.scala
- cats-effect/src/main/scala/loggerf/cats/Logful.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerA.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerEither.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerEitherT.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerOption.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerOptionT.scala
- cats-effect/src/main/scala/loggerf/cats/Loggers.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/Log.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/Logful.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerA.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerEither.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerEitherT.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerOption.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerOptionT.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/Loggers.scala
* All Loggers for Casts Effect => `loggerf.cats`
* All Loggers for Scalaz Effect => `loggerf.scalaz`
> Moved: packages

- build.sbt
- cats-effect/src/test/scala/loggerf/cats/LogSpec.scala
- core/src/test/scala/loggerf/LoggerForTesting.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LogSpec.scala
> Added: Tests for Log

- cats-effect/src/test/scala/loggerf/cats/LoggerASpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerEitherSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerEitherTSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerOptionSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerOptionTSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerASpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerEitherSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerEitherTSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerOptionSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerOptionTSpec.scala
Added: Tests for the rest of Loggers
> Added: Tests for the rest of Loggers

- cats-effect/src/main/scala/loggerf/cats/LoggerEitherT.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerOptionT.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerEitherT.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerOptionT.scala
Refactored: `LoggerOptionT` and `LoggerEitherT`
> Refactored: LoggerOptionT and LoggerEitherT

- build.sbt
Changed: `build.sbt`
* Added: The locations of jar files to be GitHub released
> Changed: build.sbt

- build.sbt
Updated: bintray config - VCS URL
> Updated: bintray config - VCS URL

- .github/workflows/release.yml
Changed: Automatic sync to Maven Central
> Changed: Automatic sync to Maven Central

- docs/docs/docs/index.md
- docs/docs/index.md
Updated: docs
* Getting Started page
* build status and artifact badges
> Updated: docs

- README.md
> Added: README.md

- .github/workflows/publish-github-pages.yml
- README.md
Added: GitHub Actions config for publishing docs
> Added: GitHub Actions config for publishing docs

- build.sbt
- docs/docs/docs/index.md
Added: More info to the Getting Started page
> Added: More info to the Getting Started page

- docs/docs/docs/index.md
Added: More example code to the Getting Started page
> Added: More example code to the Getting Started page

- build.sbt
Updated: docs - Enabled: GitHub links and social media links
> Updated: docs - Enabled: GitHub links and social media links

- build.sbt
Updated: sbt config to aggregate sub-projects and ignore packaging the root
> Updated: sbt config to aggregate sub-projects and ignore packaging the root

- docs/docs/docs/cats-effect/index.md
- docs/docs/docs/cats-effect/log.md
- docs/docs/docs/scalaz-effect/index.md
- docs/docs/docs/scalaz-effect/log.md
> Updated: docs - WIP

- build.sbt
Close #55 - Upgrade Effectie to `0.4.0`
> Close #55 - Upgrade Effectie to 0.4.0

- docs/docs/docs/index.md
Updated: docs with latest LoggerF info
> Updated: docs with latest LoggerF info

- docs/docs/docs/cats-effect/log.md
Added: An example for `Log[F].log(F[A])`
> Added: An example for Log[F].log(F[A])

- build.sbt
Close #63 - Upgrade Effectie: 0.4.0 => 1.0.0
> Close #63 - Upgrade Effectie: 0.4.0 => 1.0.0

- build.sbt
> Upgraded: Ammonite REPL

- cats-effect/src/test/scala/loggerf/cats/LogSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerEitherSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerEitherTSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LogSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerEitherSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerEitherTSpec.scala
> Fixed: Typos in test code

- .github/workflows/release.yml
Changed: GitHub Actions to publish to Maven Central in parallel
> Changed: GitHub Actions to publish to Maven Central in parallel

- changelogs/0.3.0.md
- project/ProjectInfo.scala
> logger-f v0.3.0

- .github/workflows/release.yml
Fixed: Bug in GitHub Actions to release logger-f
> Fixed: Bug in GitHub Actions to release logger-f

- changelogs/0.3.1.md
- project/ProjectInfo.scala
No changes. Re-release due to release failure of last version (v0.3.0).
> logger-f v0.3.1

- .github/workflows/release.yml
Fixed: Bug in GitHub Actions to release logger-f (No more parallel as it causes error)
> Fixed: Bug in GitHub Actions to release logger-f (No more parallel)

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
- sbt-logging/src/main/scala/loggerf/sbt/SbtLogger.scala
Close #74 - Add `loggerf.Logger` for sbt (sbt's `util-logging`).
> Close #74 - Add loggerf.Logger for sbt

- docs/docs/docs/index.md
Updated: docs - `logger-f-sbt-logging` info and new version info (for Scalaz Effect)
> Updated: docs - logger-f-sbt-logging info and new version info (for Scalaz Effect)

- build.sbt
- project/build.properties
- project/plugins.sbt
Upgraded: sbt `1.3.10` => `1.3.13` and plugins + clean up
> Upgraded: sbt 1.3.10 => 1.3.13 and plugins + clean up

- .github/workflows/build.yml
- .github/workflows/publish-github-pages.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build.sh
- build.sbt
* Scala 2.12.11 => 2.12.12
* Changes as required by new Scala versions
> Upgraded: Scala

- build.sbt
Close #84 - Upgrade effectie to 1.1.0
> Close #84 - Upgrade effectie to 1.1.0

- docs/cats-effect/log.md
- docs/getting-started.md
- docs/scalaz-effect/log.md
Updated: Changes in docs in accordance with the changes in the new version (1.0.0)
> Updated: Changes in docs

- build.sbt
Close #94 - Upgrade effectie to 1.2.0
> Close #94 - Upgrade effectie to 1.2.0

- changelogs/1.1.0.md
- project/ProjectInfo.scala
* Upgrade effectie to 1.2.0 (#94)
> logger-f v1.1.0

- docs/getting-started.md
Updated: docs with new version info
> Updated: docs with new version info

- build.sbt
- core/src/main/scala/loggerf/logger/Logger.scala
- core/src/main/scala/loggerf/syntax/LogSyntax.scala
- core/src/test/scala/loggerf/logger/LoggerForTesting.scala
- log4j/src/main/scala-2.11/loggerf/logger/Log4jCompat.scala
- log4j/src/main/scala-2.12_2.13/loggerf/logger/Log4jCompat.scala
- log4j/src/main/scala/loggerf/logger/Log4jLogger.scala
- sbt-logging/src/main/scala/loggerf/logger/SbtLogger.scala
- slf4j/src/main/scala/loggerf/logger/Slf4JLogger.scala
Close #98 - Make logging methods in `Logger` lazy
> Close #98 - Make logging methods in Logger lazy

- cats-effect/src/main/scala/loggerf/cats/Log.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerA.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerEither.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerEitherT.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerOption.scala
- cats-effect/src/main/scala/loggerf/cats/LoggerOptionT.scala
- cats-effect/src/main/scala/loggerf/cats/Loggers.scala
- core/src/main/scala/loggerf/logger/CanLog.scala
- core/src/main/scala/loggerf/syntax/LogSyntax.scala
- core/src/test/scala/loggerf/logger/LoggerForTesting.scala
- log4j/src/main/scala/loggerf/logger/Log4jLogger.scala
- sbt-logging/src/main/scala/loggerf/logger/SbtLogger.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/Log.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerA.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerEither.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerEitherT.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerOption.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/LoggerOptionT.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/Loggers.scala
- slf4j/src/main/scala/loggerf/logger/Slf4JLogger.scala
Close #100 - Change `loggerf.logger.Logger` to something other than `Logger`
> Close #100 - Change loggerf.logger.Logger to something other than Logger

- docs/cats-effect/log.md
- docs/getting-started.md
- docs/scalaz-effect/log.md
Updated: docs - with new version info
> Updated: docs - with new version info

- .github/workflows/build.yml
- .github/workflows/maven_central_sync.sh
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
- build.sbt
Changed: build and release have been simplified and more restricted
> Changed: build and release have been simplified and more restricted

- .github/workflows/build.yml
- README.md
- docs/getting-started.md
> Fixed: build all

- build.sbt
- project/plugins.sbt
* Added: sbt-updates
* Upgraded: Hedgehog => 0.4.2
> Added sbt-updates and Upgraded Hedgehog

- build.sbt
- log4s/src/main/scala/loggerf/logger/Log4sLogger.scala
> Close #108 - Support Log4s

- build.sbt
Upgraded: Effectie 1.2.0 => 1.3.0
> Upgraded: Effectie 1.2.0 => 1.3.0

- build.sbt
- docs/getting-started.md
- project/plugins.sbt
Automatically replace the versions in the doc site with the actual version from `build.sbt`
> Automatically replace the versions in the doc site with the actual version from build.sbt

- changelogs/1.3.0.md
- project/ProjectInfo.scala
* Support Log4s (#108)
* Upgrade Effectie to 1.3.0
> logger-f v1.3.0

- build.sbt
- cats-effect/src/main/scala/loggerf/cats/Log.scala
- cats-effect/src/test/scala/loggerf/cats/LogSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerASpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerEitherSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerEitherTSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerOptionSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerOptionTSpec.scala
- scalaz-effect/src/main/scala/loggerf/scalaz/Log.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LogSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerASpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerEitherSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerEitherTSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerOptionSpec.scala
- scalaz-effect/src/test/scala/loggerf/scalaz/LoggerOptionTSpec.scala
Upgraded: effectie 1.3.0 => 1.4.0
> Upgraded: effectie 1.3.0 => 1.4.0

- build.sbt
Upgraded: Hedgehog 0.4.2 => 0.5.1
> Upgraded: Hedgehog 0.4.2 => 0.5.1

- cats-effect/src/main/scala/loggerf/cats/Log.scala
- cats-effect/src/test/scala/loggerf/cats/LogSpec.scala
Close #120 - Add logPure to Log
> Close #120 - Add logPure to Log

- .gitignore
> Added: .bsp to .gitignore

- docs/cats-effect/log.md
- docs/getting-started.md
- docs/scalaz-effect/log.md
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
> Upgraded: Docusaurus

- project/build.properties
> Upgraded: 1.4.0 => 1.4.1

- website/package-lock.json
- website/package.json
Upgraded: Docusaurus `2.0.0-alpha.65` => `2.0.0-alpha.66`
> Upgraded: Docusaurus 2.0.0-alpha.65 => 2.0.0-alpha.66

- changelogs/1.4.0.md
- project/ProjectInfo.scala
* Add `logPure` to `Log` (#120)
> logger-f v1.4.0

- project/build.properties
> Upgraded: 1.4.1 => 1.4.2

- project/build.properties
Close #131 - Publish using sbt `1.3.13`
> Close #131 - Publish using sbt 1.3.13

- build.sbt
Close #134 - Upgrade Effectie to `1.6.0`
> Close #134 - Upgrade Effectie to 1.6.0

- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
- project/build.properties
> Upgraded: 1.3.13 => 1.4.3

- project/build.properties
> Upgraded: 1.4.3 => 1.4.4

- .github/workflows/maven_central_sync.sh
- build.sbt
- logger-f-monix/src/main/scala/loggerf/monix/Log.scala
- logger-f-monix/src/main/scala/loggerf/monix/Logful.scala
- logger-f-monix/src/main/scala/loggerf/monix/LoggerA.scala
- logger-f-monix/src/main/scala/loggerf/monix/LoggerEither.scala
- logger-f-monix/src/main/scala/loggerf/monix/LoggerEitherT.scala
- logger-f-monix/src/main/scala/loggerf/monix/LoggerOption.scala
- logger-f-monix/src/main/scala/loggerf/monix/LoggerOptionT.scala
- logger-f-monix/src/main/scala/loggerf/monix/Loggers.scala
- logger-f-monix/src/main/scala/loggerf/monix/package.scala
- logger-f-monix/src/test/scala/loggerf/monix/LogSpec.scala
- logger-f-monix/src/test/scala/loggerf/monix/LoggerASpec.scala
- logger-f-monix/src/test/scala/loggerf/monix/LoggerEitherSpec.scala
- logger-f-monix/src/test/scala/loggerf/monix/LoggerEitherTSpec.scala
- logger-f-monix/src/test/scala/loggerf/monix/LoggerOptionSpec.scala
- logger-f-monix/src/test/scala/loggerf/monix/LoggerOptionTSpec.scala
Close #143 - Add Monix support
> Close #143 - Add Monix support

- README.md
- build.sbt
- docs/getting-started.md
- docs/monix/log.md
- docs/monix/monix.md
- website/docusaurus.config.js
- website/sidebars.js
Updated: docs with the new version info + logger-f-monix
> Updated: docs with the new version info + logger-f-monix

- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
Fixed: The wrong timestamps in the artifacts
> Fixed: The wrong timestamps in the artifacts

- project/build.properties
> Upgraded: sbt 1.4.4 => 1.4.7

- .github/workflows/build.yml
- .github/workflows/make-docusaurus.yml
- .github/workflows/manual-build.yml
- .github/workflows/manual-github-release.yml
- .github/workflows/manual-maven-central-sync.yml
- .github/workflows/manual-publish-github-pages.yml
- .github/workflows/manual-publish.yml
- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Close #149 - Support Scala 3.0.0-M3
> Close #149 - Support Scala 3.0.0-M3

- build.sbt
Upgraded: ammonite 2.2.0 => 2.3.8
> Upgraded: ammonite 2.2.0 => 2.3.8

- build.sbt
- project/plugins.sbt
Upgraded: plugins and ammonite
> Upgraded: plugins and ammonite

- .github/workflows/build.yml
- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Close #154 - Support Scala 3.0.0-RC1
> Close #154 - Support Scala 3.0.0-RC1

- .github/workflows/build.yml
- .github/workflows/manual-build.yml
- .github/workflows/manual-github-release.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
- build.sbt
Close #156 - Upgrade Scala `2.13.3` to `2.13.4`
> Close #156 - Upgrade Scala 2.13.3 to 2.13.4

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/manual-build.yml
- .github/workflows/manual-github-upload-artifacts-and-publish.yml
- .github/workflows/manual-maven-central-sync.yml
- .github/workflows/manual-publish.yml
More publish option in GitHub Actions
> More publish option in GitHub Actions

- .github/workflows/build.yml
- .github/workflows/sbt-build-all.sh
- build.sbt
- project/build.properties
- project/plugins.sbt
Close #160 - Support Scala `3.0.0-RC2` and Scala `3.0.0-RC3`
> Close #160 - Support Scala 3.0.0-RC2 and Scala 3.0.0-RC3

- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Updated: GitHub Actions - config for release
> Updated: GitHub Actions - config for release

- build.sbt
* Support Scala `3.0.0-RC2` and Scala `3.0.0-RC3` (#160)
> logger-f v1.10.0

- .github/workflows/build.yml
- build.sbt
- project/ProjectInfo.scala
- project/plugins.sbt
Close #169 - Support Scala `3.0.0`
> Close #169 - Support Scala 3.0.0

- .github/workflows/build.yml
- changelogs/1.11.0.md
> logger-f v1.11.0

- build.sbt
Updated: docs with the new version info
> Updated: docs with the new version info

- website/package-lock.json
- website/package.json
Fixed: Doc site's vulnerabilities with `npm audit fix`.
> Fixed: Doc site's vulnerabilities with npm audit fix

- build.sbt
- project/build.properties
- project/plugins.sbt
Upgraded: sbt and plugins
- sbt `1.5.4` => `1.5.5`
- sbt-mdoc `2.2.20` => `2.2.22`
- sbt-docusaur `0.5.0` => `0.6.0`
- sbt-devoops `2.4.1` => `2.6.0`
> Upgraded: sbt and plugins

- docs/cats-effect/log.md
- docs/getting-started.md
- docs/monix/log.md
- docs/scalaz-effect/log.md
Updated: docs in accordance with the latest release
> Updated: docs in accordance with the latest release

- build.sbt
- website/package-lock.json
- website/package.json
Upgraded: Docusaurus to `2.0.0-beta.3`
> Upgraded: Docusaurus to 2.0.0-beta.3

- .github/workflows/build.yml
- build.sbt
Close #184 - Drop Scala `2.11` support
> Close #184 - Drop Scala 2.11 support

- build.sbt
- cats-effect3/src/main/scala/loggerf/cats/Log.scala
- cats-effect3/src/main/scala/loggerf/cats/Logful.scala
- cats-effect3/src/main/scala/loggerf/cats/LoggerA.scala
- cats-effect3/src/main/scala/loggerf/cats/LoggerEither.scala
- cats-effect3/src/main/scala/loggerf/cats/LoggerEitherT.scala
- cats-effect3/src/main/scala/loggerf/cats/LoggerOption.scala
- cats-effect3/src/main/scala/loggerf/cats/LoggerOptionT.scala
- cats-effect3/src/main/scala/loggerf/cats/Loggers.scala
- cats-effect3/src/main/scala/loggerf/cats/package.scala
- cats-effect3/src/test/scala/loggerf/cats/LogSpec.scala
- cats-effect3/src/test/scala/loggerf/cats/LoggerASpec.scala
- cats-effect3/src/test/scala/loggerf/cats/LoggerEitherSpec.scala
- cats-effect3/src/test/scala/loggerf/cats/LoggerEitherTSpec.scala
- cats-effect3/src/test/scala/loggerf/cats/LoggerOptionSpec.scala
- cats-effect3/src/test/scala/loggerf/cats/LoggerOptionTSpec.scala
- cats-effect3/src/test/scala/loggerf/cats/testing/ConcurrentSupport.scala
- cats-effect3/src/test/scala/loggerf/cats/testing/IoAppUtils.scala
Close #185 - Support Cats Effect 3
> Close #185 - Support Cats Effect 3

- .github/workflows/release.yml
Increase the max memory allocation for JVM used by sbt when releasing: `-J-Xmx2048m` => `-J-Xmx4096m`
> Increase the max memory allocation for JVM used by sbt when releasing: `-J-Xmx2048m` => `-J-Xmx4096m`

- .github/workflows/release.yml
Increase the stack size on JVM used by sbt when releasing
> Increase the stack size on JVM used by sbt when releasing

- .github/workflows/release.yml
Fix: Out of memory issue in CI
> Fix: Out of memory issue in CI

- docs/getting-started.md
Updated: docs with the new release info
> Updated: docs with the new release info

- build.sbt
Close #194 - Upgrade Effectie to `1.14.0`
> Close #194 - Upgrade Effectie to 1.14.0

- cats-effect/src/main/scala-3/loggerf/cats/Log.scala
- cats-effect/src/main/scala-3/loggerf/cats/LoggerA.scala
- cats-effect/src/main/scala-3/loggerf/cats/LoggerEither.scala
- cats-effect/src/main/scala-3/loggerf/cats/LoggerEitherT.scala
- cats-effect/src/main/scala-3/loggerf/cats/LoggerOption.scala
- cats-effect/src/main/scala-3/loggerf/cats/LoggerOptionT.scala
- cats-effect/src/main/scala-3/loggerf/cats/Loggers.scala
> Issue #196 - Renaming

- cats-effect3/src/main/scala-3/loggerf/cats/Log.scala
- cats-effect3/src/main/scala-3/loggerf/cats/LoggerA.scala
- cats-effect3/src/main/scala-3/loggerf/cats/LoggerEither.scala
- cats-effect3/src/main/scala-3/loggerf/cats/LoggerEitherT.scala
- cats-effect3/src/main/scala-3/loggerf/cats/LoggerOption.scala
- cats-effect3/src/main/scala-3/loggerf/cats/LoggerOptionT.scala
- cats-effect3/src/main/scala-3/loggerf/cats/Loggers.scala
> Issue #197 - Renaming

- changelogs/1.14.0.md
* Upgrade Effectie to `1.14.0` (#194)
* Write Scala 3 code for `logger-f-cats-effect` (#196)
* Write Scala 3 code for `logger-f-cats-effect3` (#197)
* Write Scala 3 code for `logger-f-monix` and `logger-f-scalaz` (#200)
> logger-f v1.14.0

- build.sbt
- cats-effect/src/main/scala-2/loggerf/cats/Log.scala
- cats-effect/src/main/scala-2/loggerf/cats/LoggerA.scala
- cats-effect/src/main/scala-2/loggerf/cats/LoggerEither.scala
- cats-effect/src/main/scala-2/loggerf/cats/LoggerEitherT.scala
- cats-effect/src/main/scala-2/loggerf/cats/LoggerOption.scala
- cats-effect/src/main/scala-2/loggerf/cats/LoggerOptionT.scala
- cats-effect/src/main/scala-2/loggerf/cats/Loggers.scala
- cats-effect/src/main/scala-3/loggerf/cats/Log.scala
- cats-effect/src/main/scala-3/loggerf/cats/LoggerA.scala
- cats-effect/src/main/scala-3/loggerf/cats/LoggerEither.scala
- cats-effect/src/main/scala-3/loggerf/cats/LoggerEitherT.scala
- cats-effect/src/main/scala-3/loggerf/cats/LoggerOption.scala
- cats-effect/src/main/scala-3/loggerf/cats/LoggerOptionT.scala
- cats-effect/src/main/scala-3/loggerf/cats/Loggers.scala
- cats-effect/src/test/scala/loggerf/cats/LogSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerASpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerEitherSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerEitherTSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerOptionSpec.scala
- cats-effect/src/test/scala/loggerf/cats/LoggerOptionTSpec.scala
Close #207 - Upgrade Effectie to `1.15.0`
> Close #207 - Upgrade Effectie to 1.15.0

- build.sbt
Close #214 - Upgrade Effectie to `1.16.0`
> Close #214 - Upgrade Effectie to 1.16.0

- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Upgraded: Docusaurus `2.0.0-beta.3` => `2.0.0-beta.6`
> Upgraded: Docusaurus 2.0.0-beta.3 => 2.0.0-beta.6

- website/package-lock.json
- website/package.json
Upgraded: Docusaurus `2.0.0-beta.6` => `2.0.0-beta.8` / docusaurus-lunr-search `2.1.14` => `2.1.15`
> Upgraded: Docusaurus 2.0.0-beta.6 => 2.0.0-beta.8 / docusaurus-lunr-search 2.1.14 => 2.1.15

- .github/pr-labeler.yml
- .github/workflows/pr-labeler.yml
Add: `pr-labeler.yml` to GitHub Actions for auto PR labelling
> Add: pr-labeler.yml to GitHub Actions for auto PR labelling

- build.sbt
Close #229: Publish to s01.oss.sonatype.org (the new Maven central)
> Close #229: Publish to s01.oss.sonatype.org (the new Maven central)

- project/plugins.sbt
Close #229: Update `sbt-ci-release` to `1.5.10`
> Close #229: Update sbt-ci-release to 1.5.10

- build.sbt
Close #229: Fix snapshot setup
> Close #229: Fix snapshot setup

- project/build.properties
Upgrade: sbt `1.5.5` => `1.5.7`
> Upgrade: sbt 1.5.5 => 1.5.7

- .github/dependabot.yml
Add `dependabot.yml` in GitHub Actions
> Add dependabot.yml in GitHub Actions

- build.sbt
Close #239 - Upgrade logback to solve CVE-2021-42550
> Close #239 - Upgrade logback to solve CVE-2021-42550

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
Update: GitHub Actions - doc site build
> Update: GitHub Actions - doc site build

- .github/pr-labeler.yml
Update: `pr-labeler.yml` - update => dependencies
> Update: pr-labeler.yml - update => dependencies

- docs/cats-effect/cats-effect.md
- docs/getting-started.md
- docs/monix/monix.md
- docs/scalaz-effect/scalaz-effect.md
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Upgrade: Docusaurus `2.0.0-beta.8` => `2.0.0-beta.14`
> Upgrade: Docusaurus 2.0.0-beta.8 => 2.0.0-beta.14

- .github/pr-labeler.yml
Update: PR labeler config for documentation and publish-docs
> Update: PR labeler config for documentation and publish-docs

- project/build.properties
Upgrade: sbt `1.5.7` => `1.6.1`
> Upgrade: sbt 1.5.7 => 1.6.1

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- project/plugins.sbt
Close #255 - Set up Codecov in GitHub Actions
> Close #255 - Set up Codecov in GitHub Actions

- .scalafmt.conf
- build.sbt
Update: .scalafmt.conf - `3.2.1` => `3.3.1`
> Update: .scalafmt.conf - 3.2.1 => 3.3.1

- .github/workflows/build.yml
- .github/workflows/release.yml
- .github/workflows/sbt-build-all.sh
- .github/workflows/sbt-build.sh
Update: build config for `logger-f-1`
> Update: build config for logger-f-1

- modules/logger-f-cats-effect/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats/src/test/scala/loggerf/future/instancesSpec.scala
- modules/logger-f-core/src/main/scala-2/loggerf/future/syntax.scala
- modules/logger-f-core/src/test/scala/loggerf/future/syntaxSpec.scala
- modules/logger-f-monix/src/test/scala/loggerf/monix/syntaxSpec.scala
> Format code

- .scalafmt.conf
Upgrade: .scalafmt.conf `3.3.1` => `3.4.3`
> Upgrade: .scalafmt.conf 3.3.1 => 3.4.3

- codecov.yml
Add: `codecov.yml` with ignore paths
> Add: codecov.yml with ignore paths

- modules/logger-f-cats-effect/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect3/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats/src/main/scala-2/loggerf/cats/instances.scala
- modules/logger-f-cats/src/main/scala-2/loggerf/cats/show.scala
- modules/logger-f-cats/src/main/scala-2/loggerf/cats/syntax/LogMessageSyntax.scala
- modules/logger-f-cats/src/main/scala-2/loggerf/cats/syntax/LogSyntax.scala
- modules/logger-f-cats/src/main/scala-3/loggerf/cats/syntax/LogMessageSyntax.scala
- modules/logger-f-cats/src/main/scala-3/loggerf/cats/syntax/LogSyntax.scala
- modules/logger-f-cats/src/test/scala/loggerf/future/instancesSpec.scala
- modules/logger-f-cats/src/test/scala/loggerf/future/syntaxSpec.scala
- modules/logger-f-core/src/main/scala-2/loggerf/core/Log.scala
- modules/logger-f-core/src/main/scala-2/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/src/main/scala-3/loggerf/LeveledMessage.scala
- modules/logger-f-core/src/main/scala-3/loggerf/core/Log.scala
- modules/logger-f-core/src/test/scala/loggerf/future/instancesSpec.scala
- modules/logger-f-core/src/test/scala/loggerf/future/syntaxSpec.scala
- modules/logger-f-monix/src/test/scala/loggerf/monix/instancesSpec.scala
- modules/logger-f-monix/src/test/scala/loggerf/monix/syntaxSpec.scala
* Change: `[_]` => `[*]`
* Format code
> Change `[_]` => `[*]` and Format code

- .scalafmt.conf
Update: `.scalafmt.conf` - additional align token
> Update: .scalafmt.conf - additional align token

- build.sbt
- modules/logger-f-core/shared/src/test/scala/loggerf/core/LogForTesting.scala
Issue #263 - Upgrade Effectie from `2.0.0-SNAPSHOT` to `2.0.0-beta1`
> Issue #263 - Upgrade Effectie from `2.0.0-SNAPSHOT` to `2.0.0-beta1`

- .github/workflows/release.yml
- version.sbt
Update: `version.sbt` - reset to `2.0.0-SNAPSHOT`
> Update: version.sbt - reset to 2.0.0-SNAPSHOT

- build.sbt
- project/plugins.sbt
Upgrade: sbt-plugins
* sbt-devoops `2.16.0` => `2.19.0`
* sbt-docusaur `0.9.0` => `0.10.0`
> Upgrade: sbt-plugins

- project/plugins.sbt
Upgrade: sbt-devoops 2.19.0 => 2.20.0
> Upgrade: sbt-devoops 2.19.0 => 2.20.0

- project/plugins.sbt
Upgrade sbt plugins sbt-devoops `2.20.0` => `2.22.0` / sbt-docusaur `0.10.0` => `0.11.0`
> Upgrade sbt plugins sbt-devoops 2.20.0 => 2.22.0 / sbt-docusaur 0.10.0 => 0.11.0

- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogMessageSyntax.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogMessageSyntax.scala
Close #307 - Add `ignoreA(A)` syntax
> Close #307 - Add `ignoreA(A)` syntax

- project/plugins.sbt
Add: `plugins.sbt` - `sbt-devoops-starter`
> Add: plugins.sbt - sbt-devoops-starter

- website/src/css/custom.css
[docs] Update CSS to use `Nerd Font` imported from `content-fonts`
> [docs] Update CSS to use Nerd Font imported from content-fonts

- build.sbt
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/core/LogForTesting.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/instancesSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/syntaxSpec.scala
Close #311 - Upgrade effectie to `2.0.0-beta2`
> Close #311 - Upgrade effectie to 2.0.0-beta2

- build.sbt
> Fix: the version in the docs

- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats/shared/src/main/scala-2/loggerf/cats/syntax/LogSyntax.scala
- modules/logger-f-cats/shared/src/main/scala-3/loggerf/cats/syntax/LogSyntax.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/future/instancesSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/future/syntaxSpec.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/future/instancesSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/future/syntaxSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/instancesSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/syntaxSpec.scala
Close #314 - Remove `logPure()`
> Close #314 - Remove logPure()

- build.sbt
Close #316 - Upgrade log libraries
> Close #316 - Upgrade log libraries

- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/instancesSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/syntaxSpec.scala
> Update test - minor changes

- modules/logger-f-cats/shared/src/main/scala-2/loggerf/syntax/LogSyntax.scala
> Minor clean up

- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
Update: `syntax` tests - add test with `ignoreA`
> Update: syntax tests - add test with ignoreA

- version.sbt
Update: `version.sbt` - back to `2.0.0-SNAPSHOT`
> Update: version.sbt - back to 2.0.0-SNAPSHOT

- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/loggingSyntaxSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/showSpec.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/ExtraSyntax.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/all.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/ExtraSyntax.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/all.scala
Close #342 - Add `debugAWith`, `infoAWith`, `warnAWith`, `errorAWith` taking `Prefix`
> Close #342 - Add debugAWith, infoAWith, warnAWith, errorAWith taking Prefix

- project/plugins.sbt
Bump sbt-devoops `2.22.0` => `2.23.0` / sbt-docusaur `0.11.0` => `0.12.0`
> Bump sbt-devoops 2.22.0 => 2.23.0 / sbt-docusaur 0.11.0 => 0.12.0

- project/build.properties
Bump sbt `1.8.0-RC1` => `1.8.0`
> Bump sbt 1.8.0-RC1 => 1.8.0

- .scalafmt.conf
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/testing/ConcurrentSupport.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/testing/IoAppUtils.scala
- modules/logger-f-cats/shared/src/main/scala-2/loggerf/syntax/LogSyntax.scala
- modules/logger-f-cats/shared/src/main/scala-3/loggerf/instances/cats.scala
- modules/logger-f-cats/shared/src/main/scala-3/loggerf/syntax/LogSyntax.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/extraSyntaxSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/loggingSyntaxSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/showSpec.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/logger/LoggerForTesting.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/syntax/LeveledMessageSyntaxSpec.scala
- modules/logger-f-log4j/shared/src/main/scala/loggerf/logger/Log4jLogger.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/instancesSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/syntaxSpec.scala
Update: `.scalafmt.conf` - `3.4.3` => `3.6.1` / `trailingCommas`: `keep` => `multiple`
> Update: `.scalafmt.conf` - `3.4.3` => `3.6.1` / `trailingCommas`: `keep` => `multiple`

- build.sbt
Update: `build.sbt` - minor changes
> Update: build.sbt - minor changes

- build.sbt
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/extraSyntaxSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/loggingSyntaxSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/instancesSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/syntaxSpec.scala
Close #351 - Bump Effectie to `2.0.0-beta3`
> Close #351 - Bump Effectie to `2.0.0-beta3`

- build.sbt
- modules/logger-f-cats/shared/src/main/scala-2/loggerf/instances/cats.scala
- modules/logger-f-cats/shared/src/main/scala-2/loggerf/syntax/LogSyntax.scala
- modules/logger-f-cats/shared/src/main/scala-3/loggerf/instances/cats.scala
- modules/logger-f-cats/shared/src/main/scala-3/loggerf/syntax/LogSyntax.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/loggingSyntaxSpec.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/instances/future.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/instances/future.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/core/LogForTesting.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
Close #355 - Add `log_` returning `F[Unit]`
> Close #355 - Add `log_` returning `F[Unit]`

- modules/logger-f-cats/shared/src/main/scala-2/loggerf/instances/cats.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala
Change `Log.EF` from `val` to `def`
> Change `Log.EF` from `val` to `def`

- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/ToLog.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/ToLog.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
Close #358 - Add `logS(String)(String => LogMessage with NotIgnorable): F[String]`
> Close #358 - Add `logS(String)(String => LogMessage with NotIgnorable): F[String]`

- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogSyntax.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
Close #359 - Add `logS_(String)(String => LogMessage with NotIgnorable): F[Unit]`
> Close #359 - Add `logS_(String)(String => LogMessage with NotIgnorable): F[Unit]`

- build.sbt
Close #362 - Upgrade effectie to `2.0.0-beta4`
> Close #362 - Upgrade effectie to 2.0.0-beta4

- version.sbt
Update: version.sbt 2.0.0-beta4 => back to 2.0.0-SNAPSHOT
> Update: version.sbt 2.0.0-beta4 => back to 2.0.0-SNAPSHOT

- .github/workflows/checks.yml
- .scalafix-scala2.conf
- .scalafix-scala3.conf
- build.sbt
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/testing/ConcurrentSupport.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/core/LogForTesting.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/logger/LoggerForTesting.scala
- project/plugins.sbt
Close #370 - Enable Scalafmt and Scalafix checks
> Close #370 - Enable Scalafmt and Scalafix checks

- build.sbt
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/testing/IoAppUtils.scala
Close #372 - Upgrade effectie to 2.0.0-beta5 and cats to 2.7.0
- Also bump extras from 0.4.0 to 0.25.0
> Close #372 - Upgrade effectie to 2.0.0-beta5 and cats to 2.7.0

- version.sbt
Update: `version.sbt` `2.0.0-beta5` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt 2.0.0-beta5 => back to 2.0.0-SNAPSHOT

- modules/logger-f-slf4j/shared/src/main/scala/loggerf/logger/Slf4JLogger.scala
Fix #376 - Dynamic log level change is not applied for Slf4J logger
> Fix #376 - Dynamic log level change is not applied for Slf4J logger

- version.sbt
Update: version.sbt `2.0.0-beta6` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt `2.0.0-beta6` => back to `2.0.0-SNAPSHOT`

- build.sbt
- docs/cats-effect/log.md
> Update: Docs

- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- website/docusaurus.config.js
- website/package-lock.json
- website/package.json
Upgrade: Docusaurus `2.0.0-beta.17` => `2.3.0`
> Upgrade: Docusaurus `2.0.0-beta.17` => `2.3.0`

- website/package.json
Bump `docusaurus-lunr-search`: `2.1.15` => `2.3.2`
> Bump `docusaurus-lunr-search`: `2.1.15` => `2.3.2`

- docs/latest/getting-started.md
> Update: `getting-started.md`

- docs/latest/cats/log.md
Update: `log.md` - `Log` `String`
> Update: `log.md` - `Log` `String`

- .github/workflows/coverage.yml
- .github/workflows/release.yml
GitHub Actions - separate test coverage from build and release - `coverage.yml`
> GitHub Actions - separate test coverage from build and release - coverage.yml

- version.sbt
Update: version.sbt `2.0.0-beta7` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt 2.0.0-beta7 => back to 2.0.0-SNAPSHOT

- .github/workflows/build.yml
- .github/workflows/coverage.yml
- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/release.yml
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
Update: GitHub Actions config - `olafurpg/setup-scala` => `actions/setup-java`
> Update: GitHub Actions config - `olafurpg/setup-scala` => `actions/setup-java`

- changelogs/2.0.0-beta7.md
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/instancesSpec.scala
Fix release note for 2.0.0-beta7
> Fix release note for 2.0.0-beta7

- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/loggingSyntaxSpec.scala
- version.sbt
Update: version.sbt `2.0.0-beta8` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt 2.0.0-beta8 => back to 2.0.0-SNAPSHOT

- build.sbt
Close #400 - Upgrade `effectie` to `2.0.0-beta6`
> Close #400 - Upgrade effectie to 2.0.0-beta6

- version.sbt
Update: version.sbt `2.0.0-beta9` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt 2.0.0-beta9 => back to 2.0.0-SNAPSHOT

- docs/latest/cats/log.md
Update: docs - `log.md`: more about `log(F[A])`
> Update: docs - log.md: more about log(F[A])

- docs/latest/cats/log.md
Update: docs - `log.md`: update `logS` and `logS_`
> Update: docs - log.md: update logS and logS_

- docs/latest/cats/log.md
Update: docs - `log.md`: update `log(F[A])`
> Update: docs - `log.md`: update `log(F[A])`

- README.md
- docs/latest/cats/log.md
Update: docs - `log.md` and `README.md`
> Update: docs - `log.md` and `README.md`

- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/loggingSyntaxSpec.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala/loggerf/logger/CanLog.scala
Close #410 - Add missing implicit instance messages
> Close #410 - Add missing implicit instance messages

- docs/latest/cats/cats.md
- docs/latest/cats/import.md
- docs/latest/cats/log.md
- website/src/css/custom.css
Update: docs - with what to import (`import.md`) and set `max-width` for container to `80%`
> Update: docs - with what to import (`import.md`) and set `max-width` for container to `80%`

- build.sbt
Close #413 - Upgrade Effectie to `2.0.0-beta7`
> Close #413 - Upgrade Effectie to `2.0.0-beta7`

- version.sbt
Update: `version.sbt` - `2.0.0-beta10` => back to `2.0.0-SNAPSHOT`
> # Summary Update: `version.sbt` - `2.0.0-beta10` => back to `2.0.0-SNAPSHOT`

- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/extraSyntaxSpec.scala
- website/docusaurus.config.js
- website/src/pages/versions.js
Update: docs - with more version info + the latest version (`2.0.0-beta10`)
> Update: docs - with more version info + the latest version (2.0.0-beta10)

- build.sbt
- modules/logger-f-core/shared/src/test/scala/loggerf/core/LogForTesting.scala
Close #420 - Upgrade Effectie to `2.0.0-beta8`
> Close #420 - Upgrade Effectie to `2.0.0-beta8`

- docs/latest/cats/log.md
Update: docs for effectie `2.0.0-beta8`
> Update: docs for effectie 2.0.0-beta8

- version.sbt
Update: `version.sbt` - `2.0.0-beta11` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt - 2.0.0-beta11 => back to 2.0.0-SNAPSHOT

- website/docusaurus.config.js
- website/src/pages/versions.js
Update: docs with the latest logger-f version info
> Update: docs with the latest logger-f version info

- docs/latest/cats/log.md
Update: docs - `log.md`: add `log` for `OptionT[F, A]`
> Update: docs - log.md: add log for OptionT[F, A]

- docs/latest/cats/log.md
Update: docs - `log.md`: add `log` for `EitherT[F, A, B]`
> Update: docs - `log.md`: add `log` for `EitherT[F, A, B]`

- build.sbt
Close #428 - Upgrade effectie to `2.0.0-beta9`
> Close #428 - Upgrade effectie to `2.0.0-beta9`

- version.sbt
Update: `version.sbt` - `2.0.0-beta12` => back to `2.0.0-SNAPSHOT`
> Update: `version.sbt` - `2.0.0-beta12` => back to `2.0.0-SNAPSHOT`

- website/docusaurus.config.js
- website/src/pages/versions.js
Update: docs with the latest version info
> Update: docs with the latest version info

- codecov.yml
Update: `codecov.yml` - Add PR comment layout
> Update: `codecov.yml` - Add PR comment layout

- README.md
Update: README.md - Add Codecov test coverage
> Update: README.md - Add Codecov test coverage

- build.sbt
- modules/logger-f-logback-mdc-monix3/shared/src/main/scala/loggerf/logger/logback/MonixMdcAdapter.scala
- modules/logger-f-logback-mdc-monix3/shared/src/test/scala/loggerf/logger/logback/Gens.scala
- modules/logger-f-logback-mdc-monix3/shared/src/test/scala/loggerf/logger/logback/MonixMdcAdapterSpec.scala
- modules/logger-f-logback-mdc-monix3/shared/src/test/scala/loggerf/logger/logback/types.scala
Close #438 - Add `MdcAdapter` for Monix to properly share context through `MDC` with `Task` and Local from Monix
> Close #438 - Add MdcAdapter for Monix to properly share context through MDC with Task and Local from Monix

- modules/logger-f-logback-mdc-monix3/shared/src/main/scala/loggerf/logger/logback/Monix3MdcAdapter.scala
Fix #444 - `Monix3MdcAdapter.initialize()` is broken for logback `1.4.8`
> Fix #444 - `Monix3MdcAdapter.initialize()` is broken for logback `1.4.8`

- version.sbt
Update: `version.sbt` - `2.0.0-beta14` => back to `2.0.0-SNAPSHOT`
> Update: version.sbt - 2.0.0-beta14 => back to 2.0.0-SNAPSHOT

- build.sbt
- modules/logger-f-core/shared/src/test/scala/loggerf/core/LogForTesting.scala
Close #448 - Upgrade effectie to `2.0.0-beta10`
> Close #448 - Upgrade effectie to 2.0.0-beta10

- version.sbt
Update: version.sbt - 2.0.0-beta15 => back to 2.0.0-SNAPSHOT
> Update: version.sbt - 2.0.0-beta15 => back to 2.0.0-SNAPSHOT

- website/docusaurus.config.js
- website/src/pages/versions.js
Update docs - add the previous versions to publish the current version doc
> Update docs - add the previous versions to publish the current version doc

- build.sbt
Close #457 - Upgrade `effectie` to `2.0.0-beta11`
> Close #457 - Upgrade `effectie` to `2.0.0-beta11`

- version.sbt
Update: `version.sbt` - `2.0.0-beta17` => back to `2.0.0-SNAPSHOT`
> Update: `version.sbt` - `2.0.0-beta17` => back to `2.0.0-SNAPSHOT`

- .github/workflows/checks.yml
- .github/workflows/release.yml
- project/build.properties
Bump sbt to 1.9.3 and fix java options: `JVM_OPTS` => `JAVA_OPTS`
> Bump sbt to 1.9.3 and fix java options: `JVM_OPTS` => `JAVA_OPTS`

- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/triesSpec.scala
- modules/logger-f-core/shared/src/main/scala/loggerf/instances/tries.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/triesSpec.scala
Close #469 - Add `Log` instance for `Try` - `Log[Try]`
> Close #469 - Add `Log` instance for `Try` - `Log[Try]`

- version.sbt
Update: `version.sbt` - reset to `2.0.0-SNAPSHOT`
> Update: `version.sbt` - reset to `2.0.0-SNAPSHOT`

- build.sbt
Close #478 - Upgrade Effectie to `2.0.0-beta12`
> Close #478 - Upgrade Effectie to `2.0.0-beta12`

- build.sbt
Close #480 - Upgrade logback to `1.4.8`
> Close #480 - Upgrade logback to `1.4.8`

- .scalafmt.conf
> Bump scalafmt to 3.7.14

- build.sbt
Close #488 - Upgrade `effectie` to `2.0.0-beta13`
> Close #488 - Upgrade `effectie` to `2.0.0-beta13`

- project/build.properties
> Upgrade sbt to `1.9.6`

- website/docusaurus.config.js
- website/src/pages/versions.js
Update docs - with the latest version info
> Update docs - with the latest version info

- project/build.properties
> Upgrade sbt to 1.9.7

- website/docusaurus.config.js
- website/src/pages/versionsArchived.json
Update: docs with the latest info
> Update: docs with the latest info

- .github/workflows/checks.yml
- .scalafix-scala2.conf
- .scalafix-scala3.conf
- build.sbt
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/extraSyntaxSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/futureSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/idSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/loggingSyntaxSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/triesSpec.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogMessageSyntax.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/triesSpec.scala
- modules/logger-f-logback-mdc-monix3/shared/src/test/scala/loggerf/logger/logback/Monix3MdcAdapterSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/instancesSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/syntaxSpec.scala
- project/plugins.sbt
Upgrade sbt and sbt plugins / Clean up
* sbt-devoops to `3.0.0`
* sbt-docusaur to `0.15.0`
* Clean up the code as suggested by `sbt-tpolecat`
> Upgrade sbt and sbt plugins / Clean up

- build.sbt
Close #508 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.2.0`
> Close #508 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.2.0`

- version.sbt
logger-f v2.0.0-beta23 - update version.sbt
> logger-f v2.0.0-beta23 - update version.sbt

- build.sbt
Close #514 - Upgrade effectie to 2.0.0-beta14
> Close #514 - Upgrade effectie to 2.0.0-beta14

- website/docusaurus.config.js
Update docs: Make the sidebar menu hidable
> Update docs: Make the sidebar menu hidable

- .github/workflows/coverage.yml
GitHub Actions: Add separate test coverage build (`coverage.yml`) with Codecov
> GitHub Actions: Add separate test coverage build (`coverage.yml`) with Codecov

- website/docusaurus.config.js
- website/src/pages/versionsArchived.json
Update docs with the latest version info
> Update docs with the latest version info

- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/instancesSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/extraSyntaxSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/futureSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/idSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/loggingSyntaxSpec.scala
- modules/logger-f-cats/shared/src/test/scala/loggerf/instances/triesSpec.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogMessageSyntax.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/triesSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/instancesSpec.scala
- modules/logger-f-monix/shared/src/test/scala/loggerf/monix/syntaxSpec.scala
Close #543 - Fix discard non-unit value
> Close #543 - Fix discard non-unit value

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/coverage.yml
- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/release.yml
- build.sbt
- project/plugins.sbt
Close #541 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.6.0` and `logback` to `1.4.12`
> Close #541 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.6.0` and `logback` to `1.4.12`

- .github/workflows/build.yml
- .github/workflows/checks.yml
- .github/workflows/coverage.yml
- .github/workflows/doc-site-build-only.yml
- .github/workflows/doc-site-publish.yml
- .github/workflows/manual-build.yml
- .github/workflows/manual-github-release.yml
- .github/workflows/manual-github-upload-artifacts-and-publish.yml
- .github/workflows/manual-publish.yml
- .github/workflows/release.yml
Close #567 - GitHub Actions: `sbt` is missing in the build
- Also update SBT options (`SBT_OPTS`) across workflow files for improved performance
> Close #567 - GitHub Actions: sbt is missing in the build

- build.sbt
> Reformat `build.sbt`

- build.sbt
Close #617 - Bump Scala 3 to 3.1.3
> Close #617 - Bump Scala 3 to 3.1.3

- modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/LogMessage.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogMessageSyntax.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/LeveledMessage.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala
- modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogMessageSyntax.scala
- modules/logger-f-core/shared/src/main/scala/loggerf/logger/CanLog.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/logger/LoggerForTesting.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/syntax/LeveledMessageSyntaxSpec.scala
- modules/logger-f-core/shared/src/test/scala/loggerf/test_data/Gens.scala
- modules/logger-f-log4j/shared/src/main/scala/loggerf/logger/Log4jLogger.scala
- modules/logger-f-log4s/shared/src/main/scala/loggerf/logger/Log4sLogger.scala
- modules/logger-f-sbt-logging/shared/src/main/scala/loggerf/logger/SbtLogger.scala
- modules/logger-f-slf4j/shared/src/main/scala/loggerf/logger/Slf4JLogger.scala
- modules/logger-f-test-kit/shared/src/main/scala/loggerf/testing/CanLog4Testing.scala
- modules/logger-f-test-kit/shared/src/test/scala/loggerf/testing/CanLog4TestingSpec.scala
- modules/test-logger-f-core/shared/src/test/scala/core_testing/CanLogForTesting.scala
Close #631: Add log with Throwable
> Close #631: Add log with Throwable

- project/build.properties
Close #633: Bump sbt to 1.11.6
> Close #633: Bump sbt to 1.11.6

- website/docusaurus.config.js
Update docs: with the latest version info
> Update docs: with the latest version info

- website/docusaurus.config.ts
- website/package.json
Update docs: Add DocSearch with Algolia
> Update docs: Add DocSearch with Algolia
