core/src/main/scala/loggerf/Logful.scala, core/src/main/scala/loggerf/LoggerA.scala, core/src/main/scala/loggerf/LoggerEither.scala, core/src/main/scala/loggerf/LoggerEitherT.scala, core/src/main/scala/loggerf/LoggerOption.scala, core/src/main/scala/loggerf/LoggerOptionT.scala, core/src/main/scala/loggerf/Loggers.scala
Changed: val names of `EffectConstructor[F]` and `Monad[F]` from `FE0` to `EF0` and `FM0` to `MF0` respectively
=> Changed: val names of EffectConstructor[F] and Monad[F]

.github/workflows/build.yml
Fixed: Wrong step names for build with Scala 2.13 in GitHub Actions
=> Fixed: Wrong step names for build with Scala 2.13 in GitHub Actions

build.sbt, changelogs/0.1.0.md
* Log with log level (#22)
* `Log.log(F[A])(aToString)`
* `Log.log(F[Option[A]])(ifEmptyWithLogLevel, aToStringWithLogLevel)`
* `Log.log(F[Either[A, B]])(aToStringWithLogLevel, bToStringWithLogLevel)`
* `Log.log(OptionT[F, A])(ifEmptyWithLogLevel, aToStringWithLogLevel)`
* `Log.log(EitherT[F, A, B])(aToStringWithLogLevel, bToStringWithLogLevel)`
The following ones are experimental and might be removed in the future.
* LoggerA for `F[A]`
* LoggerOption for `F[Option[A]]`
* LoggerOptionT for `OptionT[F, A]`
* LoggerEither for `F[Either[A, B]]`
* LoggerEitherT for `EitherT[F, A, B]`
=> logger-f v0.1.0

cats-effect/src/main/scala/loggerf/cats/Log.scala, cats-effect/src/main/scala/loggerf/cats/Logful.scala, cats-effect/src/test/scala/loggerf/cats/LogSpec.scala, scalaz-effect/src/main/scala/loggerf/scalaz/Log.scala, scalaz-effect/src/main/scala/loggerf/scalaz/Logful.scala, scalaz-effect/src/test/scala/loggerf/scalaz/LogSpec.scala
Close #50 - Add `log()(ignore)` to skip logging
=> Close #50 - Add log()(ignore) to skip logging

build.sbt
Upgraded: 
* Scala 2.13.1 => 2.13.2
* Ammonite REPL 2.0.4 => 2.1.1 and it's also enabled for Scala 2.12
=> Upgraded: Scala and Ammonite REPL

.github/workflows/build.yml
GitHub Actions - different Java versions for different Scala versions when building
* Java 8 for Scala 2.11
* Java 11 for Scala 2.12
* Java 11 for Scala 2.13
=> GitHub Actions - different Java versions for different Scala versions when building

.github/workflows/release.yml
GitHub Actions - different Java versions for different Scala versions when releasing
* Java 8 for Scala 2.11
* Java 11 for Scala 2.12
* Java 11 for Scala 2.13
=> GitHub Actions - different Java versions for different Scala versions when releasing

changelogs/0.2.0.md, project/ProjectInfo.scala
* Add `log()(ignore)` to skip logging (#50)
* Upgrade Effectie to 0.4.0 (#55)
=> logger-f v0.2.0

changelogs/0.4.0.md, project/ProjectInfo.scala
* Add `loggerf.Logger` for sbt (#74)
* Replace `master` branch with `main` branch (#73)
=> logger-f v0.4.0

core/src/test/scala/loggerf/logger/LoggerForTesting.scala, log4j/src/main/scala/loggerf/logger/Log4jLogger.scala, sbt-logging/src/main/scala/loggerf/logger/SbtLogger.scala, slf4j/src/main/scala/loggerf/logger/Slf4JLogger.scala
Close #90 - Add a way to set an internal `Logger` when creating `loggerf.logger.Logger`
=> Close #90 - Add a way to set an internal Logger when creating loggerf.logger.Logger

changelogs/1.0.0.md, project/ProjectInfo.scala
* Upgrade [effectie](https://kevin-lee.github.io/effectie) to 1.1.0 (#84)
* Simplify import (#88)
The old logger-f requires to import classes like this.
```scala
import loggerf.Logger
import loggerf.Slf4JLogger
import loggerf.cats.Log
import loggerf.cats.Log.LeveledMessage._
import loggerf.cats.Logful._
```  
It looks unorganized and hard to find which ones to import. So it's been simplified to
```scala
import loggerf.cats._
import loggerf.logger._
import loggerf.syntax._
```
* Add a way to set an internal Logger when creating loggerf.logger.Logger (#90)
=> logger-f v1.0.0

.github/workflows/release.yml
Added: 5 second delay has been added to each Maven Central sync to give the Sonatype repo some time to close staging
=> Added: 5 second delay has been added to each Maven Central sync

changelogs/1.2.0.md, project/ProjectInfo.scala
* Make logging methods in `Logger` lazy (#98)
* Change `loggerf.logger.Logger` to something other than `Logger` (#100) - It's now `CanLog`.
=> logger-f v1.2.0

build.sbt
Fix #113 - Log4s support is missing in publish
=> Fix #113 - Log4s support is missing in publish

changelogs/1.3.1.md, project/ProjectInfo.scala
* Log4s support is missing in publish (#113)
=> logger-f v1.3.1

.github/workflows/maven_central_sync.sh
Updated: `maven_central_sync.sh` to include `logger-f-log4s` when publishing to Maven
=> Updated: maven_central_sync.sh to include logger-f-log4s when publishing to Maven

changelogs/1.5.0.md, project/ProjectInfo.scala
* Support Dotty (Scala `3.0.0-M1`) (#130)
* Publish using sbt `1.3.13` (#131)
* Upgrade Effectie to `1.6.0` (#134)
=> logger-f v1.5.0

.github/workflows/build.yml, .github/workflows/release.yml, build.sbt
Close #138 - Support Dotty (Scala 3.0.0-M2)
* Also upgrade Effectie from `1.6.0` to `1.7.0`
=> Close #138 - Support Dotty (Scala 3.0.0-M2)

changelogs/1.6.0.md, project/ProjectInfo.scala
* Support Dotty (Scala `3.0.0-M2`) (#138)
* Upgrade Effectie to `1.7.0`
=> logger-f v1.6.0

changelogs/1.7.0.md, project/ProjectInfo.scala
* Add Monix support (#143)
* Upgrade Effectie to `1.8.0`
=> logger-f v1.7.0

changelogs/1.8.0.md, project/ProjectInfo.scala
* Support Scala 3.0.0-M3 (#149)
=> logger-f v1.8.0

changelogs/1.9.0.md, project/ProjectInfo.scala
* Upgrade Scala `2.13.3` to `2.13.4` (#156)
* Support Scala `3.0.0-RC1` (#154)
=> logger-f v1.9.0

build.sbt
Upgraded: Scala `2.12.12` => `2.12.13` / `2.13.4` => `2.13.5`
=> Upgraded: Scala 2.12.12 => 2.12.13 / 2.13.4 => 2.13.5

changelogs/1.10.0.md
* Support Scala `3.0.0-RC2` and Scala `3.0.0-RC3` (#160)
=> logger-f v1.10.0

changelogs/1.12.0.md
* Upgrade `effectie` to `1.12.0` (#178)
- Use `Fx` instead of `EffectConstructor`
=> logger-f v1.12.0

.github/workflows/release.yml
Fix: Increase the stack size on JVM used by sbt when releasing
=> Fix: Increase the stack size on JVM used by sbt when releasing

changelogs/1.13.0.md
* Drop Scala `2.11` support (#184)
* Support Cats Effect 3 (#185)
=> logger-f v1.13.0

changelogs/1.15.0.md
* Upgrade Effectie to `1.15.0` (#207)
=> logger-f v1.15.0

changelogs/1.16.0.md
* Upgrade Effectie to `1.16.0` (#214)
=> logger-f v1.16.0 🎃

build.sbt, project/plugins.sbt
Close #220 - Bump log4j to fix RCE 0-day exploit found in log4j CVE-2021-44228
=> Close #220 - Bump log4j to fix RCE 0-day exploit found in log4j CVE-2021-44228

.github/workflows/release.yml
Update: GitHub Actions - release does not upload artifacts to GitHub release
=> Update: GitHub Actions - release does not upload artifacts to GitHub release

changelogs/1.17.0.md
* Bump log4j to fix RCE 0-day exploit found in `log4j` CVE-2021-44228 (#220)
=> logger-f v1.17.0

build.sbt
Close #225 - Bump log4j to fix CVE-2021-45046
=> Close #225 - Bump log4j to fix CVE-2021-45046

changelogs/1.18.0.md
* Bump `log4j` to fix CVE-2021-45046 (#225)
=> logger-f v1.18.0

changelogs/1.19.0.md
* Upgrade `logback` to `1.2.9` to solve CVE-2021-42550 (#239)
=> logger-f v1.19.0

build.sbt
Close #242 - Upgrade Log4J to 2.17.0 to solve CVE-2021-45105
=> Close #242 - Upgrade Log4J to 2.17.0 to solve CVE-2021-45105

changelogs/1.20.0.md
* Upgrade Log4J to `2.17.0` to solve CVE-2021-45105 (#242)
=> logger-f v1.20.0

build.sbt
Close #275 - Stop releasing `logger-f-cats-effect`, `logger-f-cats-effect3` and `logger-f-monix`
=> Close #275 - Stop releasing logger-f-cats-effect, logger-f-cats-effect3 and logger-f-monix

modules/logger-f-core/src/main/scala-2/loggerf/core/ToLog.scala, modules/logger-f-core/src/main/scala-2/loggerf/syntax/LeveledMessageSyntax.scala, modules/logger-f-core/src/main/scala-3/loggerf/core/ToLog.scala, modules/logger-f-core/src/main/scala-3/loggerf/syntax/LeveledMessageSyntax.scala, modules/logger-f-core/src/test/scala/loggerf/core/LogForTesting.scala, modules/logger-f-core/src/test/scala/loggerf/syntax/LeveledMessageSyntaxSpec.scala
Close #280 - Add `ToLog[A]` type-class to support logging type `A`
=> Close #280 - Add ToLog[A] type-class to support logging type A

modules/logger-f-cats/src/main/scala-2/loggerf/cats/show.scala, modules/logger-f-cats/src/main/scala-3/loggerf/cats/show.scala, modules/logger-f-cats/src/test/scala/loggerf/cats/showSpec.scala
Close #283 - `ToLog` type-class instance using `cats.Show`
=> Close #283 - ToLog type-class instance using cats.Show

build.sbt, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala, modules/logger-f-core/shared/src/test/scala/loggerf/future/instancesSpec.scala, modules/logger-f-core/shared/src/test/scala/loggerf/future/syntaxSpec.scala, modules/logger-f-core/shared/src/test/scala/loggerf/syntax/LeveledMessageSyntaxSpec.scala
Close #318 - Remove `effectie-syntax` from the `logger-f-core` project
=> Close #318 - Remove `effectie-syntax` from the `logger-f-core` project

modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/instancesSpec.scala, modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala, modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/instancesSpec.scala, modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/syntaxSpec.scala, modules/logger-f-cats/shared/src/main/scala-2/loggerf/instances/cats.scala, modules/logger-f-cats/shared/src/main/scala-3/loggerf/instances/cats.scala, modules/logger-f-monix/shared/src/test/scala/loggerf/monix/instancesSpec.scala, modules/logger-f-monix/shared/src/test/scala/loggerf/monix/syntaxSpec.scala
Close #321 - Move `loggerf.cats.instances.logF` to `loggerf.instances.cats`
=> Close #321 - Move `loggerf.cats.instances.logF` to `loggerf.instances.cats`

modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/instancesSpec.scala, modules/logger-f-cats-effect/shared/src/test/scala/loggerf/cats/syntaxSpec.scala, modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/instancesSpec.scala, modules/logger-f-cats-effect3/shared/src/test/scala/loggerf/cats/syntaxSpec.scala, modules/logger-f-cats/shared/src/main/scala-2/loggerf/cats/syntax/all.scala, modules/logger-f-cats/shared/src/main/scala-2/loggerf/syntax/LogMessageSyntax.scala, modules/logger-f-cats/shared/src/main/scala-2/loggerf/syntax/LogSyntax.scala, modules/logger-f-cats/shared/src/main/scala-2/loggerf/syntax/all.scala, modules/logger-f-cats/shared/src/main/scala-2/loggerf/syntax/logging.scala, modules/logger-f-cats/shared/src/main/scala-3/loggerf/cats/syntax/all.scala, modules/logger-f-cats/shared/src/main/scala-3/loggerf/syntax/LogMessageSyntax.scala, modules/logger-f-cats/shared/src/main/scala-3/loggerf/syntax/LogSyntax.scala, modules/logger-f-cats/shared/src/main/scala-3/loggerf/syntax/all.scala, modules/logger-f-cats/shared/src/main/scala-3/loggerf/syntax/logging.scala, modules/logger-f-cats/shared/src/test/scala/loggerf/future/syntaxSpec.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala, modules/logger-f-monix/shared/src/test/scala/loggerf/monix/instancesSpec.scala, modules/logger-f-monix/shared/src/test/scala/loggerf/monix/syntaxSpec.scala
Close #322 - Change `loggerf.cats.syntax` to `loggerf.syntax`
=> Close #322 - Change loggerf.cats.syntax to loggerf.syntax

modules/logger-f-cats/shared/src/test/scala/loggerf/instances/instancesSpec.scala, modules/logger-f-cats/shared/src/test/scala/loggerf/instances/showSpec.scala, modules/logger-f-cats/shared/src/test/scala/loggerf/instances/syntaxSpec.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/instances/future.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogSyntax.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/instances/future.scala, modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala, modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala
Close #329 - `loggerf.future.instances.logFuture` => `loggerf.instances.future.logFuture`
=> Close #329 - loggerf.future.instances.logFuture => loggerf.instances.future.logFuture

changelogs/2.0.0-beta2.md, version.sbt
* Add `ignoreA(A)` syntax (#307)
```scala
val fa: F[Option[A]] = ...
log(fa)(info("Not found"), ignoreA)
fa.log(info("Not found"), ignoreA)
// If None, log "Not found"
// If Some(value), ignore logging
```
```scala
val fab: F[Either[A, B]] = ...
log(fab)(ignoreA, b => info(s"It's Right($b)"))
fab.log(ignoreA, b => info(s"It's Right($b)"))
// If Left, ignore logging
// If Right, log
```
```scala
val fab: F[Either[A, B]] = ...
log(fab)(a => info(s"It's Left($a)"), ignoreA)
fab.log(a => info(s"It's Left($a)"), ignoreA)
// If Left, log
// If Right, ignore logging
```
* Upgrade `effectie` to `2.0.0-beta2` (#311)
* Remove `logPure()` (#314)
* `logPure()` is unnecessary as `log()` should use `pureOf` internally instead of `effectOf`.
* Upgrade log libraries (#316)
* `SLF4J`: `1.7.30` => `1.7.36` …
=> logger-f v2.0.0-beta2

modules/logger-f-core/shared/src/main/scala-2/loggerf/core/ToLog.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/ToLog.scala, modules/logger-f-core/shared/src/test/scala/loggerf/core/ToLogSpec.scala
Close #335 - Add `ToLog.by[A](A => String): ToLog[A]`
=> Close #335 - Add ToLog.by[A](A => String): ToLog[A]

modules/logger-f-core/shared/src/main/scala-2/loggerf/core/ToLog.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/ToLog.scala, modules/logger-f-core/shared/src/test/scala/loggerf/core/ToLogSpec.scala
Close #334 - Add `ToLog` instance for `String` (`ToLog[String]`)
=> Close #334 - Add ToLog instance for String (ToLog[String])

modules/logger-f-core/shared/src/main/scala-2/loggerf/core/ToLog.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/ToLog.scala, modules/logger-f-core/shared/src/test/scala/loggerf/core/ToLogSpec.scala
Close #339 - Add `ToLog.fromToString[A]` to construct an instance of `ToLog[A]`
=> Close #339 - Add ToLog.fromToString[A] to construct an instance of ToLog[A]

modules/logger-f-cats/shared/src/main/scala-2/loggerf/syntax/all.scala, modules/logger-f-cats/shared/src/main/scala-2/loggerf/syntax/extra.scala, modules/logger-f-cats/shared/src/main/scala-3/loggerf/syntax/all.scala, modules/logger-f-cats/shared/src/main/scala-3/loggerf/syntax/extra.scala, modules/logger-f-cats/shared/src/test/scala/loggerf/instances/extraSyntaxSpec.scala, modules/logger-f-cats/shared/src/test/scala/loggerf/instances/loggingSyntaxSpec.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/ExtraSyntax.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/all.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/extra.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/logging.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/ExtraSyntax.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/all.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/extra.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/logging.scala, modules/logger-f-core/shared/src/test/scala/loggerf/core/ToLogSpec.scala
Close #337 - Add `prefix(String): Prefix` and other methods to use it
* `Prefix(String => String)`
* Scala 2:
```scala
def debug(prefix: Prefix): String => LogMessage with NotIgnorable
def info(prefix: Prefix): String => LogMessage with NotIgnorable
def warn(prefix: Prefix): String => LogMessage with NotIgnorable
def error(prefix: Prefix): String => LogMessage with NotIgnorable
```
* Scala 3:
```scala
def debug(prefix: Prefix): String => LeveledMessage
def info(prefix: Prefix): String => LeveledMessage
def warn(prefix: Prefix): String => LeveledMessage
def error(prefix: Prefix): String => LeveledMessage
```
=> Close #337 - Add prefix(String): Prefix and other methods to use it

build.sbt
Close #363 - Bump logging libraries
- Slf4J 1.7.36 => 2.0.6
- Logback 1.2.11 => 1.4.5
=> Close #363 - Bump logging libraries

changelogs/2.0.0-beta4.md, version.sbt
* Add `log_` returning `F[Unit]` (#355)
```scala
Log[F].log_(pureOf("blah"))(info) // log info blah then returns F[Unit]
log_(pureOf("blah"))(info) // log info blah then returns F[Unit]
```
* Add `logS(String)(String => LogMessage with NotIgnorable): F[String]` (#358)
```scala
logS(String)(String => LogMessage with NotIgnorable): F[String]
String.logS(String => LogMessage with NotIgnorable): F[String]
```
* Add `logS_(String)(String => LogMessage with NotIgnorable): F[Unit]` (#359)
```scala
logS_(String)(String => LogMessage with NotIgnorable): F[Unit]
String.logS_(String => LogMessage with NotIgnorable): F[Unit]
```
* Bump Effectie to `2.0.0-beta4` (#362)
* Bump logging libraries (#363)
* Slf4J `1.7.36` => `2.0.6`
* Logback `1.2.11` => `1.4.5`
=> logger-f v2.0.0-beta4

modules/logger-f-core/shared/src/main/scala/loggerf/logger/CanLog.scala
Close #368 - Fix `non-private` `val` in `GetLogger` which is for extension methods for `CanLog`
=> Close #368 - Fix `non-private` `val` in `GetLogger` which is for extension methods for `CanLog`

changelogs/2.0.0-beta5.md, version.sbt
* Fix `non-private` `val` in `GetLogger` which is for extension methods for `CanLog` (#368)
* Upgrade `effectie` to `2.0.0-beta5` and `cats` to `2.7.0` (#372)
* Enable Scalafmt and Scalafix checks (#370)
=> logger-f v2.0.0-beta5

changelogs/2.0.0-beta6.md, version.sbt
* Fix: Dynamic log level change is not applied for Slf4J logger (#376)
=> logger-f v2.0.0-beta6

.github/workflows/manual-github-release.yml, .github/workflows/manual-github-upload-artifacts-and-publish.yml, .github/workflows/manual-publish.yml, .github/workflows/sbt-build-all.sh, .github/workflows/sbt-build.sh, build.sbt, modules/logger-f-core/shared/src/main/scala-2/loggerf/LogMessage.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/ExtraSyntax.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogMessageSyntax.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogSyntax.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/LeveledMessage.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/ToLog.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/ExtraSyntax.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogMessageSyntax.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogSyntax.scala, modules/logger-f-core/shared/src/test/scala-2/loggerf/test_data/Something.scala, modules/logger-f-core/shared/src/test/scala-3/loggerf/test_data/Something.scala, modules/logger-f-core/shared/src/test/scala/loggerf/syntax/LeveledMessageSyntaxSpec.scala, project/ProjectInfo.scala, project/build.properties, project/plugins.sbt
Close #379 - Make `logS`, `logS_` and `prefix` lazy with call-by-name and thunk
=> Close #379 - Make logS, logS_ and prefix lazy with call-by-name and thunk

modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala, modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala
Fix #379 - `logS_` does not do lazy evaluation for the message `String`
=> Fix #379 - logS_ does not do lazy evaluation for the message String

changelogs/2.0.0-beta7.md, version.sbt
* Add `logger-f-test-kit` with `CanLog` instance for testing (#388)
* Make `logS`, `logS_` and `prefix` lazy with call-by-name and thunk (#379)
=> logger-f v2.0.0-beta7

modules/logger-f-cats/shared/src/test/scala/loggerf/instances/extraSyntaxSpec.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/LogMessage.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/ExtraSyntax.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/LeveledMessage.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/ExtraSyntax.scala
Fix #395 - `debug(Prefix)`, `info(Prefix)`, `warn(Prefix)` and `error(Prefix)` do not work with `logS` and `logS_`
=> Fix #395 - `debug(Prefix)`, `info(Prefix)`, `warn(Prefix)` and `error(Prefix)` do not work with `logS` and `logS_`

changelogs/2.0.0-beta8.md, version.sbt
* `debug(Prefix)`, `info(Prefix)`, `warn(Prefix)` and `error(Prefix)` do not work with `logS` and `logS_` (#395)
=> logger-f v2.0.0-beta8

changelogs/2.0.0-beta9.md, version.sbt
* Upgrade `effectie` to `2.0.0-beta6` (#400)
=> logger-f v2.0.0-beta9

build.sbt
Close #415 - Bump and clean up libraries
- Bump: `hedgehog-extra` to `0.3.0`
- Remove `extras-cats` from `logger-f-cats` and `logger-f-test-kit` as it's not used by them.
=> Close #415 - Bump and clean up libraries

changelogs/2.0.0-beta10.md, version.sbt
* Add missing `implicit` instance messages (#410)
* Upgrade `effectie` to `2.0.0-beta7` (#413)
* Bump and clean up libraries (#415)
* Bump: `hedgehog-extra` to `0.3.0`
* Remove `extras-cats` from `logger-f-cats` and `logger-f-test-kit` as it's not used by them
=> logger-f v2.0.0-beta10

changelogs/2.0.0-beta11.md, version.sbt
* Upgrade `effectie` to `2.0.0-beta8` (#420)
=> logger-f v2.0.0-beta11

changelogs/2.0.0-beta12.md, version.sbt
* Upgrade `effectie` to `2.0.0-beta9` (#428)
=> logger-f v2.0.0-beta12

changelogs/2.0.0-beta13.md, version.sbt
* Add `MdcAdapter` for Monix to properly share context through `MDC` with `Task` and `Local` from Monix (#438)
=> logger-f v2.0.0-beta13

modules/logger-f-logback-mdc-monix3/shared/src/main/scala/loggerf/logger/logback/Monix3MdcAdapter.scala, modules/logger-f-logback-mdc-monix3/shared/src/test/scala/loggerf/logger/logback/Monix3MdcAdapterSpec.scala
Close #442 - [`logger-f-logback-mdc-monix3`] Rename `MonixMdcAdapter` to `Monix3MdcAdapter`
=> Close #442 - [`logger-f-logback-mdc-monix3`] Rename `MonixMdcAdapter` to `Monix3MdcAdapter`

changelogs/2.0.0-beta14.md, version.sbt
* [`logger-f-logback-mdc-monix3`] Renamed: `MonixMdcAdapter` to `Monix3MdcAdapter` (#442)
* Fixed: `Monix3MdcAdapter.initialize()` is broken for logback `1.4.8` (#444)
=> logger-f v2.0.0-beta14

changelogs/2.0.0-beta15.md, version.sbt
* Upgrade `effectie` to `2.0.0-beta10` (#448)
=> logger-f v2.0.0-beta15

modules/logger-f-logback-mdc-monix3/shared/src/main/scala/loggerf/logger/logback/Monix3MdcAdapter.scala, modules/logger-f-logback-mdc-monix3/shared/src/test/scala/loggerf/logger/logback/Monix3MdcAdapterSpec.scala
Close #452 - Add `initialize` method taking `Monix3MdcAdapter` in the companion object of `Monix3MdcAdapter`
=> Close #452 - Add initialize method taking Monix3MdcAdapter in the companion object of Monix3MdcAdapter

changelogs/2.0.0-beta16.md, version.sbt
* Add `initialize` method taking `Monix3MdcAdapter` in the companion object of `Monix3MdcAdapter` (#452)
=> logger-f v2.0.0-beta16

changelogs/2.0.0-beta17.md, version.sbt
* Upgrade `effectie` to `2.0.0-beta11` (#457)
=> logger-f v2.0.0-beta17

modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala
Close #463 - Add more information for `@implicitNotFound` on `Log`
=> Close #463 - Add more information for @implicitNotFound on Log

changelogs/2.0.0-beta18.md, version.sbt
* Add `Log` instance for `Try` - `Log[Try]` (#469)
=> logger-f v2.0.0-beta18

build.sbt, modules/logger-f-cats/shared/src/test/scala/loggerf/instances/futureSpec.scala, modules/logger-f-cats/shared/src/test/scala/loggerf/instances/idSpec.scala
Add more tests for Log instances
- Tests for `Log[Future]` with `loggerf.instances.future.logFuture`
- Tests for `Log[Future]` with `loggerf.instances.cats.logF`
- Tests for `Log[Id]`
=> Add more tests for Log instances

changelogs/2.0.0-beta19.md, version.sbt
* Remove unnecessary `FxCtor` from `loggerf.instances.future.logFuture` (#473)
Since `loggerf.instances.future.LogFuture` can just have `effectie.instances.future.fxCtor.fxCtorFuture`, it's not required to have `EF: FxCtor[Future]` as a parameter of `loggerf.instances.future.logFuture`.
=> logger-f v2.0.0-beta19

changelogs/2.0.0-beta20.md, version.sbt
* Upgrade effectie to `2.0.0-beta12` (#478)
* Upgrade logback to `1.4.8` (#480)
=> logger-f v2.0.0-beta20

changelogs/2.0.0-beta21.md, version.sbt
* Upgrade effectie to `2.0.0-beta13` (#488)
=> logger-f v2.0.0-beta21

modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala, modules/logger-f-core/shared/src/main/scala-2/loggerf/core/syntax/LogSyntax.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogSyntax.scala, modules/logger-f-core/shared/src/test/scala/loggerf/instances/instancesSpec.scala, modules/logger-f-core/shared/src/test/scala/loggerf/instances/syntaxSpec.scala, modules/logger-f-core/shared/src/test/scala/loggerf/test_data/Gens.scala, modules/logger-f-core/shared/src/test/scala/loggerf/test_data/TestCases.scala
Close #498 - Change the `LogMessage` parameter in the `log(F[A])` method from `NotIgnorable` to `MaybeIgnorable`
=> Close #498 - Change the `LogMessage` parameter in the `log(F[A])` method from `NotIgnorable` to `MaybeIgnorable`

modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/Log.scala
Close #500 - Remove unnecessary re-evaluation of `String` in `logS`
=> Close #500 - Remove unnecessary re-evaluation of `String` in `logS`

changelogs/2.0.0-beta22.md, version.sbt
* Change the `LogMessage` parameter in the `log(F[A])` method from `NotIgnorable` to `MaybeIgnorable` (#498)
This could be required and useful for case like
```scala
final case class Something(id: Int, name: String)
val fa: F[Something] = ...
Log[F].log(fa) {
case Something(0, _) => ignore
case Something(n, name) => info(s"Something: id=$n, name=$name")
}
```
* Remove unnecessary re-evaluation of `String` in `logS` (#500)
`msg()` and `message` (call-by-name) below in line 61 (Scala 2) and line 62 (Scala 3) were replaced with a single lazy evaluation.
https://github.com/kevin-lee/logger-f/blob/47a0ad183bf4b3b847661143e31a85c302d02146/modules/logger-f-core/shared/src/main/scala-2/loggerf/core/Log.scala#L56-L62
https://github.com/kevin-lee/logger-f/blob/47a0ad183bf4b3b847661143e31a85c302d0214 …
=> logger-f v2.0.0-beta22

docs/latest/getting-started.md
Update: docs - getting started - add how to get for scala-cli
=> Update: docs - getting started - add how to get for scala-cli

changelogs/2.0.0-beta23.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.2.0` (#508)
=> logger-f v2.0.0-beta23

build.sbt
Close #516 - Bump `logback` to `1.4.9` and `logback-scala-interop` to `0.3.0`
=> Close #516 - Bump `logback` to `1.4.9` and `logback-scala-interop` to `0.3.0`

changelogs/2.0.0-beta24.md, version.sbt
* Upgrade `effectie` to `2.0.0-beta14` (#514)
* [`logger-f-logback-mdc-monix3`] Bump `logback` to `1.4.9` and `logback-scala-interop` to `0.3.0` (#516)
=> logger-f v2.0.0-beta24

changelogs/2.0.0.md, version.sbt
* Temporarily disable `Scala.js` support (#531)
* LoggerF v2 to support Effectie v2 (#259)
It also includes all the changes in the following releases.
* Upgrade `Effectie` to `v2` (#263)
* Drop `Scalaz Effect` support (#265)
* Move `Log` typeclass to `core` and keep the instances in the sub-projects (#266)
* Add `F[A].log()` syntax and more to `logger-f-cats` (#272)
* Stop releasing `logger-f-cats-effect`, `logger-f-cats-effect3` and `logger-f-monix` (#275)
* Redesign `LeveledMessage` (#278)
* Add `ToLog[A]` type-class to support logging type `A` (#280)
* `ToLog` type-class instance using `cats.Show` (#283)
* Redesign `loggerf.core.syntax` and `loggerf.cats.syntax` (#285)
* Support `Scala.js` (#291)
---
* Add `ignoreA(A)` syntax (#307)
```scala
val fa: F[Option[A]] = ...
log(fa)(info("Not …
```
=> logger-f v2.0.0

build.sbt
Close #534 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.4.0` and `logback` to `1.4.10`
=> Close #534 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.4.0` and `logback` to `1.4.10`

changelogs/2.0.1.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.4.0` and `logback` to `1.4.10` (#534)
=> logger-f v2.0.1

build.sbt
Close #538 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.5.0` and `logback` to `1.4.11`
=> Close #538 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.5.0` and `logback` to `1.4.11`

changelogs/2.0.3.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.6.0` and `logback` to `1.4.12` (#541)
* Fix discard non-unit value (#543)
* Upgrade `effectie` to `2.0.0` (#545)
=> logger-f v2.0.3

build.sbt
Close #548 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.7.0` and `logback` to `1.4.13`
=> Close #548 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.7.0` and `logback` to `1.4.13`

changelogs/2.0.4.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.7.0` and `logback` to `1.4.13` (#548)
=> logger-f v2.0.4

build.sbt
Close #551 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.8.0` and `logback` to `1.4.14`
=> Close #551 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.8.0` and `logback` to `1.4.14`

changelogs/2.0.5.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `0.8.0` and `logback` to `1.4.14` (#551)
=> logger-f v2.0.5

build.sbt
Close #554 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.0.0` and `logback` to `1.5.0`
=> Close #554 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.0.0` and `logback` to `1.5.0`

changelogs/2.1.0.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.0.0` and `logback` to `1.5.0` (#554)
=> logger-f v2.1.0

changelogs/2.1.1.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.1.0` and `logback` to `1.5.1` (#557)
=> logger-f v2.1.1

build.sbt
Close #560 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.2.0` and `logback` to `1.5.2`
=> Close #560 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.2.0` and `logback` to `1.5.2`

changelogs/2.1.2.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.2.0` and `logback` to `1.5.2` (#560)
=> logger-f v2.1.2

build.sbt
Close #563 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.3.0` and `logback` to `1.5.3`
Bump
- slf4j to 2.0.12
- logback to 1.5.3
- logback-scala-interop to 1.3.0
=> Close #563 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.3.0` and `logback` to `1.5.3`

build.sbt, modules/logger-f-logback-mdc-monix3/shared/src/main/scala/loggerf/logger/logback/Monix3MdcAdapter.scala
Close #570 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.5.0` and `logback` to `1.5.5`
Bump
- slf4j to 2.0.13
- logback to 1.5.5
- logback-scala-interop to 1.5.0
Also use `LoggerContext.setMDCAdapter` instead of reflection.
=> Close #570 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.5.0` and `logback` to `1.5.5`

changelogs/2.1.5.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.5.0` and `logback` to `1.5.5` (#570)
Since `logback` `1.5.1`, `LoggerContext.setMDCAdapter` allows setting the inner `mdcAdapter: MDCAdapter` more than once. Previously, assigning a new `mdcAdapter` only worked when `mdcAdapter` was `null`.
So, `LoggerContext.setMDCAdapter` is used instead of reflection to set `Monix3MdcAdapter` as `LoggerContext`'s `mdcAdapter`.
=> logger-f v2.1.5

build.sbt
Close #571 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.6.0` and `logback` to `1.5.6`
=> Close #571 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.6.0` and `logback` to `1.5.6`

changelogs/2.1.6.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.6.0` and `logback` to `1.5.6` (#571)
=> logger-f v2.1.6

build.sbt
Close #572 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.7.0` and `logback` to `1.5.7`
=> Close #572 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.7.0` and `logback` to `1.5.7`

changelogs/2.1.7.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.7.0` and `logback` to `1.5.7` (#572)
=> logger-f v2.1.7

build.sbt
Close #573 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.8.0` and `logback` to `1.5.8`
=> Close #573 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.8.0` and `logback` to `1.5.8`

changelogs/2.1.8.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.8.0` and `logback` to `1.5.8` (#573)
=> logger-f v2.1.8

build.sbt
Close #574 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.9.0` and `logback` to `1.5.9`
=> Close #574 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.9.0` and `logback` to `1.5.9`

changelogs/2.1.9.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.9.0` and `logback` to `1.5.9` (#574)
=> logger-f v2.1.9

build.sbt
Close #575 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.10.0` and `logback` to `1.5.10`
=> Close #575 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.10.0` and `logback` to `1.5.10`

changelogs/2.1.10.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.10.0` and `logback` to `1.5.10` (#575)
=> logger-f v2.1.10

build.sbt
Close #576 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.11.0` and `logback` to `1.5.11`
=> Close #576 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.11.0` and `logback` to `1.5.11`

changelogs/2.1.11.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.11.0` and `logback` to `1.5.11` (#576)
=> logger-f v2.1.11

build.sbt
Close #577 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.12.0` and `logback` to `1.5.12`
=> Close #577 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.12.0` and `logback` to `1.5.12`

changelogs/2.1.12.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.12.0` and `logback` to `1.5.12` (#577)
=> logger-f v2.1.12

build.sbt
Close #578 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.13.0` and `logback` to `1.5.13`
=> Close #578 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.13.0` and `logback` to `1.5.13`

changelogs/2.1.13.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.13.0` and `logback` to `1.5.13` (#578)
=> logger-f v2.1.13

build.sbt
Close #579 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.14.0` and `logback` to `1.5.14`
=> Close #579 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.14.0` and `logback` to `1.5.14`

changelogs/2.1.14.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.14.0` and `logback` to `1.5.14` (#579)
=> logger-f v2.1.14

build.sbt
Close #580 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.15.0` and `logback` to `1.5.15`
=> Close #580 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.15.0` and `logback` to `1.5.15`

changelogs/2.1.15.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.15.0` and `logback` to `1.5.15` (#580)
=> logger-f v2.1.15

build.sbt
Close #581 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.16.0`, `slf4j` to `2.0.16` and `logback` to `1.5.16`
=> Close #581 - [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.16.0`, `slf4j` to `2.0.16` and `logback` to `1.5.16`

changelogs/2.1.16.md
* [`logger-f-logback-mdc-monix3`] Bump `logback-scala-interop` to `1.16.0`, `slf4j` to `2.0.16` and `logback` to `1.5.16` (#581)
=> logger-f v2.1.16

build.sbt, modules/logger-f-logback-mdc-monix3/shared/src/main/scala/loggerf/logger/logback/Monix3MdcAdapter.scala, modules/logger-f-logback-mdc-monix3/shared/src/test/scala/loggerf/logger/logback/Monix3MdcAdapterSpec.scala, modules/logger-f-slf4j-mdc/shared/src/main/scala/org/slf4j/SetMdcAdapter.scala
Fix #565 - [`logger-f-logback-mdc-monix3`] is not compatible with `logback` `1.5.17` due to changes in `slf4j` `2.0.17`
- Update `slf4j` to `2.0.17`, `logback` to `1.5.17` and `logback-scala-interop` to `1.17.0`
- Add `slf4j` `MDC` support to set `MDCAdapter` in `MDC`
=> Fix #565 - [`logger-f-logback-mdc-monix3`] is not compatible with `logback` `1.5.17` due to changes in `slf4j` `2.0.17`

changelogs/2.1.17.md
* [`logger-f-logback-mdc-monix3`] is not compatible with `logback` `1.5.17` due to changes in `slf4j` `2.0.17` (#565)
* Update `slf4j` to `2.0.17`, `logback` to `1.5.17` and `logback-scala-interop` to `1.17.0`
* `logback` `1.5.16` uses `slf4j` `2.0.16`.
* `logback` `1.5.17` uses `slf4j` `2.0.17`.
* Due to changes introduced in `slf4j` `2.0.17`, the current logic for initializing `Monix3MdcAdapter` fails. This is not caused by `logback`'s `LoggerContext`, but rather by `MDC` from `slf4j`.
* This fix added `slf4j` `MDC` support to set `MDCAdapter` in `MDC`
* This fix updated the initialization of `MDC` to accommodate the changes in `slf4j` `2.0.17`.
=> logger-f v2.1.17

changelogs/2.1.18.md
* [`logger-f-slf4j-mdc`][`logger-f-logback-mdc-monix3`] `SetMdcAdapter`and `Monix3MdcAdapter` are now compatible with older `slf4j` and `logback` (#612)
* Downgraded: `slf4j` to `2.0.12`, but `SetMdcAdapter` and `Monix3MdcAdapter` can also work with the latest `slf4j` (`2.0.17` at the moment).
* Downgraded: `logback` to `1.5.0` for `MDC` adapter, but `SetMdcAdapter` and `Monix3MdcAdapter` can also work with the latest `logback` (`1.5.17` at the moment).
* Downgraded: `logback-scala-interop` to `1.0.0`
=> logger-f v2.1.18

.github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/release.yml
Close #617 - Bump Scala 3 to 3.1.3 - Update GitHub Actions workflows
=> Close #617 - Bump Scala 3 to 3.1.3 - Update GitHub Actions workflows

changelogs/2.2.0.md
- Fix the last one (v2.2.0) that wasn't released.
* Bump Scala 3 to `3.1.3`
* `s01.oss.sonatype.org` will be sunset on the 30th of June, 2025. So it will be longer possible to publish the artifacts to s01.oss.sonatype.org. (#615)
=> logger-f v2.2.0

codecov.yml, modules/logger-f-cats/shared/src/main/scala-2/loggerf/instances/cats.scala, modules/logger-f-cats/shared/src/main/scala-3/loggerf/instances/cats.scala
Issue #624: Put `loggerf.instances.cats` back with `@deprecated` to guide users on how to use it without `loggerf.instances.cats`
=> Issue #624: Put `loggerf.instances.cats` back with `@deprecated` to guide users on how to use it without `loggerf.instances.cats`

changelogs/2.3.0.md
* Add `log` with `Throwable` (#631)
```scala
fa.log(a => info(throwable)(s"something $a"))
Log[F].log(fa)(a => warn(throwable)(s"something $a"))
fAorB.log(e => error(e)(s"Some error: ${e.getMessage}"), a => ignore)
```
***
* Move an instance of the `Log` typeclass from `logger-f-cats` to `logger-f-core` using `orphan-cats`.
Move `loggerf.instances.cats.LogF` to `loggerf.core.Log` with [orphan-cats](https://github.com/kevin-lee/orphan).
So, if a project using `logger-f-core` without `logger-f-cats` has `cats` as a dependency, the `Log` instance provided by `logger-f` is automatically available without any extra `import`s.
***
* Bump `sbt` to `1.11.6` (#633)
=> logger-f v2.3.0

.github/workflows/build.yml, .github/workflows/checks.yml, .github/workflows/coverage.yml, .github/workflows/doc-site-build-only.yml, .github/workflows/doc-site-publish.yml, .github/workflows/release.yml, build.sbt, modules/logger-f-cats/shared/src/main/scala-3/loggerf/instances/show.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/ToLog.scala, modules/logger-f-core/shared/src/main/scala-3/loggerf/core/syntax/LogSyntax.scala, modules/test-logger-f-core/shared/src/test/scala-3/core_testing/LogWithoutCustomInstanceSpec.scala, project/plugins.sbt
Update Scala versions and dependencies, fix Scala 3 compatibility
- Update Scala `3.1.3` -> `3.3.5` and Scala `2.13.14` -> `2.13.16`
- Update `sbt-wartremover` `3.1.6` -> `3.3.5`
- Update `sbt-scalafix` `0.10.4` -> `0.14.3`
- Update `sbt-scalafmt` `2.4.6` -> `2.5.5`
- Update `sbt-scoverage` `2.1.1` -> `2.3.1`
- Update `sbt-docusaur` `0.15.0` -> `0.17.0`
- Update `sbt-devoops` `3.1.0` -> `3.2.1`
- Fix Scala 3 `ToLog` instances to use explicit method definitions
- Remove unused Future imports from `LogSyntax`
=> Close #638: Bump Scala 3 to 3.3.5 and 2.13 to 2.13.16
